In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
df = pd.read_csv("all_seasons_clean.csv")
df.head()

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,gp,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996.0,2.0,42.0,64,3.9,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97
1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994.0,2.0,34.0,4,3.8,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97
2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993.0,1.0,12.0,41,8.3,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97
3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989.0,1.0,7.0,64,10.2,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97
4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995.0,1.0,22.0,52,2.8,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97

In [2]:
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12844 entries, 0 to 12843
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   player_name        12844 non-null  object
 1   team_abbreviation  12844 non-null  object
 2   age                12844 non-null  float64
 3   player_height      12844 non-null  float64
 4   player_weight      12844 non-null  float64
 5   college            12844 non-null  object
 6   country            12844 non-null  object
 7   draft_year         10486 non-null  float64
 8   draft_round        10433 non-null  float64
 9   draft_number       10430 non-null  float64
 10  gp                 12844 non-null  int64
 11  pts                12844 non-null  float64
 12  reb                12844 non-null  float64
 13  ast                12844 non-null  float64
 14  net_rating         12844 non-null  float64
 15  oreb_pct           12844 non-null  float64
 16  dreb_pct           12844 non-null  float64
 17  usg_pct            12844 non-null  float64
 18  ts_pct             12844 non-null  float64
 19  ast_pct            12844 non-null  float64
 20  season             12844 non-null  object
dtypes: float64(15), int64(1), object(5)
memory usage: 2.1+ MB

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,gp,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996.0,2.0,42.0,64,3.9,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97
1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994.0,2.0,34.0,4,3.8,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97
2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993.0,1.0,12.0,41,8.3,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97
3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989.0,1.0,7.0,64,10.2,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97
4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995.0,1.0,22.0,52,2.8,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97

In [3]:
df = df.drop(columns=["player_name"])

In [4]:
df["height_m"] = df["player_height"] / 100
df["BMI"] = df["player_weight"] / (df["height_m"] ** 2)

In [5]:
df["season_start"] = df["season"].str[:4].astype(int)
draft_year_numeric = pd.to_numeric(df["draft_year"], errors="coerce")
df["experience"] = df["season_start"] - draft_year_numeric

In [6]:
df["is_drafted"] = np.where(df["draft_year"] == "Undrafted",0,1)

In [7]:
df["height_category"] = pd.cut(
    df["player_height"],
    bins=[170,190,205,240],
    labels=["Guard","Wing","Big"]
)

In [8]:
df["weight_category"] = pd.cut(
    df["player_weight"],
    bins=[60,85,105,150],
    labels=["Light","Medium","Heavy"]
)

In [9]:
df = pd.get_dummies(
    df,
    columns=[
        "team_abbreviation",
        "country",
        "height_category",
        "weight_category"
    ],
    drop_first=True
)

In [10]:
df["draft_round"] = pd.to_numeric(
    df["draft_round"],
    errors="coerce"
)

df["draft_number"] = pd.to_numeric(
    df["draft_number"],
    errors="coerce"
)

In [11]:
df.isnull().sum()

age                          0
player_height                0
player_weight                0
college                      0
draft_year                2358
                          ...
country_Yugoslavia           0
height_category_Wing         0
height_category_Big          0
weight_category_Medium       0
weight_category_Heavy        0
Length: 143, dtype: int64

In [12]:
df.to_csv("all_seasons_feature_engineered.csv", index=False)
print("Feature engineered dataset saved successfully!")

Feature engineered dataset saved successfully!